### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by SVijayB** [SVijayB/PyHub#1]
## Hacktoberfest 2020

Anyone willing to add a few Python programs to the list of already existing programs can do so. 

Make sure you read the [contributing.md](https://github.com/SVijayB/PyHub/blob/master/.github/CONTRIBUTING.md) file.

Also, once you add all the programs, make sure you update the readme.md file accordingly. If the program belongs to none of the already existing categories, add it to the miscellaneous section. 

**Happy hacking!**

**Comment by AkshayaKulasekaran** [comment]
May I?

**Comment by SVijayB** [comment]
Yes, feel free to. Just fork, create a new branch, add any program you want.

**Comment by AkshayaKulasekaran** [comment]
Awesome! I'd like to add two files to basic: "input.py" and "print.py"

**Comment by SVijayB** [comment]
Alright 👍

**Comment by lee00286** [comment]
May I edit some links in readme.md file which don't direct to the right files as well?

**Comment by SVijayB** [comment]
@lee00286 Yes you can. Thanks for the help 👍

**Comment by lee00286** [comment]
@SVijayB Do I need to open an issue before to open a pull request?

**Comment by SVijayB** [comment]
Nope, it's alright. you can just send the pull request.

**Comment by TanviSutar** [comment]
@SVijayB Can I add a folder named Sorting, that holds all sorting algorithms??

**Comment by SVijayB** [comment]
@TanviSutar Yes, you may. Make sure you update the readme.md file accordingly

**Comment by lee00286** [comment]
May I add "tuple.py" file to basic?

**Comment by SVijayB** [comment]
@lee00286 Yes you can. Don't forget to update the README.md file accordingly

**Comment by pranav6670** [comment]
Can I add an image compression algorithm or something related to Image processing? Thank You!

**Comment by srshobhit72** [comment]
I would like to work!

**Comment by SVijayB** [comment]
@srshobhit72 feel free to work on it. Just fork it, create a new branch, make changes and send us a pull request. Thank you!

**Comment by SVijayB** [comment]
@pranav6670 yes, you can! Just add the folder or files into the miscellaneous folder. Make sure you update the README.md file accordingly. Thanks!

**Comment by pranav6670** [comment]
> @pranav6670 yes, you can! Just add the folder or files into the miscellaneous folder. Make sure you update the README.md file accordingly. Thanks!

Great! Thanks, man!

**Comment by SVijayB** [comment]
Hey guys! Don't forget to star the repo. You have access to a large number of python programs that you might find useful someway someday! 

Thanks :D

**Comment by OmiGitProjects** [comment]
i Would like to work

**Comment by SVijayB** [comment]
@OmiGitProjects feel free to 😄 !

**Comment by SVijayB** [comment]
## Re-opening issue for Hacktoberfest 2021

Anyone willing to add a few Python programs to the list of already existing programs can do so. 

Make sure you read the [contributing.md](https://github.com/SVijayB/PyHub/blob/master/.github/CONTRIBUTING.md) file.

Also, once you add all the programs, make sure you update the readme.md file accordingly. If the program belongs to none of the already existing categories, add it to the miscellaneous section. 

**Happy hacking!**

**Comment by pranav6670** [comment]
Can I work on a Multilayer Perceptron from scratch? This will fit an output for two inputs, like a logic table.

**Comment by SVijayB** [comment]
@pranav6670 you can put it under `Machine Learning`

**Comment by pranav6670** [comment]
Great! Thank you!

**Comment by Kraken-ops** [comment]
Sir I would like to contribute my python programs, please assign me.

**Comment by SVijayB** [comment]
@Kraken-ops go ahead, make sure the scripts are in the correct directory.

**Comment by pranav6670** [comment]
> ## Re-opening issue for Hacktoberfest 2021
> Anyone willing to add a few Python programs to the list of already existing programs can do so.
> 
> Make sure you read the [contributing.md](https://github.com/SVijayB/PyHub/blob/master/.github/CONTRIBUTING.md) file.
> 
> Also, once you add all the programs, make sure you update the readme.md file accordingly. If the program belongs to none of the already existing categories, add it to the miscellaneous section.
> 
> **Happy hacking!**

It shows that the project isn't participating in Hacktoberfest 2021 on the homepage of Hacktoberfest!

**Comment by SVijayB** [comment]
Right, I failed to add in the hacktoberfest label. Might take a while before it is updated.
