### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by SVijayB** [SVijayB/PyHub#50]
It's been a while since I've checked in on the repository, the README.md file might be a little outdated.
It would be great if someone could help me organize and update it! 
Please follow the existing format, you can reach out to me at any time if you need any help.

Thanks in advance 😄 !

**Comment by user-ank** [comment]
You can assign this to me, I can make few changes.

**Comment by SVijayB** [comment]
@user-ank assigned. Let me know if you need any help!

**Comment by user-ank** [comment]
Some topics mentioned in 'Table of contents' of Readme file are not include down in the Readme file.
Should I include those ?

**Comment by SVijayB** [comment]
@user-ank check if the directory exists with any script, if not, then remove the topic from `Table of contents` if the directory exists, then add it to the README file.

**Comment by user-ank** [comment]
Hey @SVijayB  I want to add AI and ML scripts from the folder to Readme file. Where can I get descriptions(one liner) of those scripts like the others ?

**Comment by SVijayB** [comment]
Thanks for the help @user-ank!
