### ISSUE TITLE
Add an example of how to use the singleton design pattern

### ISSUE THREAD

**Issue by jopime** [SVijayB/PyHub#55]
I think it would be interesting to add:
- Create new section "Software design pattern"
- Add example of Singleton pattern
- Add description with case of uses. 

Thanks! :)

**Comment by SVijayB** [comment]
@jopime yeah sure! Sounds good. 
If you are interested, you can work on it and I'll assign you the issue. If not I'll get to it when I am free. 

Thanks for the suggestion!

**Comment by jopime** [comment]
Yes, I'm interested ;)
I start to work on it, please assign me the issue.
Thanks

**Comment by SVijayB** [comment]
#58
