### ISSUE TITLE
Internet Speed Test

### ISSUE THREAD

**Issue by Shreejan-35** [SVijayB/PyHub#63]
I want to build a python script which will check your internet speed using certain functions 

It uses speedtest-cli library. 
Three functions will be there -
- Upload
- Download
- ping

I have some questions -
- Can I put it in socket programming folder? 
- Do I manually need to add the details in main README.md file? 

Pls answer

**Comment by SVijayB** [comment]
Hey @Shreejan-35, put it in the `Miscellaneous` folder and well, if you find it too hard to update the README file, just add a comment at the beginning of the script that describes it.
